- build: examples/1-audio-over-tcp
  argon: [1.3.1, 1.4.0, latest]
  boron: [latest]
  xenon: [latest]
- build: examples/2-audio-over-tcp-16bit
  argon: [latest]
- build: more-examples/1-sdfat
  boron: [latest]
